import turtle
turtle.shape("turtle")
turtle.speed(0)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.exitonclick()
